# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: InvtAI-tokensale-contract

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['18']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install dependencies
      run: |
        npm install -s
        mkdir -p "data/abi"
    - name: Run testcase
      run: npm run test
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        GOERLI_URL: ${{ secrets.GOERLI_URL }}
        MAINNET_URL: ${{ secrets.MAINNET_URL }}
        ARBITRUM_GOERLI_URL: ${{ secrets.ARBITRUM_GOERLI_URL }}
        ARBITRUM_URL: ${{ secrets.ARBITRUM_URL }}
        ETHER_SCAN_APIKEY: ${{ secrets.ETHER_SCAN_APIKEY }}
